#!/bin/sh

db_host="$1"
shift
cmd="$@"

while ! mysqladmin ping -h "$db_host" --silent; do
  >&2 echo "MySQL is unavailable - sleeping ..."
  sleep 1
done

>&2 echo "MySQL is up - executing command"
exec $cmd

