Supplier: !include Supplier.raml
SupplierArray: !include SupplierArray.raml
SupplierAddress: !include SupplierAddress.raml
SupplierAddressArray: !include SupplierAddressArray.raml
SupplierContact: !include SupplierContact.raml
SupplierContactsArray: !include SupplierContactsArray.raml