type: object
displayName: SupplierConstact
description: Object representing all contacts associated with a given supplier.
properties:
    contactId:
        type: string
    supplierId:
        type: string
    title:
        type: string
    contactType:
        type: string
    firstName:
        type: string
    lastName:
        type: string
    email:
        type: string
    phone:
        type: string
    mobile:
        type: string
    department:
        type: string
    fax:
        type: string
    changedBy:
        type: string
    createdBy:
        type: string
example: !include ../examples/SupplierContact.json
