type: object
displayName: Supplier
description: Object representing a single supplier item.
properties:
    supplierId:
        type: string
        description: Internal identifier of tradingPartner (humanReadable, i.e. alphanumeric). Ideally we generate a proposal based on name field by stripping spaces and invalid special chars, if required append a number for uniqueness, e.g. OpusCapita Software GmbH -> opuscapitasoftwaregmbh
        required: true
    supplierName:
        type: string
        description: The official name of the company as registered, e.g. OpusCapita Software GmbH
        required: true
    foundedOn:
        type: string
    legalForm:
        type: string
    commercialRegisterNo:
        type: string
    cityOfRegistration:
        type: string
        description: City where the company is registered.
    countryOfRegistration:
        type: string
        description: Country where company is registered. It should country iso code, e.g. DE for Germany.
    taxIdentificationNo:
        type: string
        required: false
        description: A Tax Identification Number or TIN is an identifying number used for tax purposes in the United States. It may be assigned by the Social Security Administration or by the IRS (Internal Revenue Service.)
    vatIdentificationNo:
        type: string
        required: false
        description: A value added tax identification number or VAT identification number (VATIN) is an identifier used in many countries, including the countries of the European Union, for value added tax purposes. VATIN uses a 2 digit prefix to denote country which in most cases is iso 639-1 alpha2 congruent.
    globalLocationNo:
        type: string
        description: Global Location Number as given out by GS1 member organizations. First three digits is country code e.g. 400 - Germany
    homePage:
        type: string
        description: Company homepage url.
    dunsNo:
        type: string
        required: false
        description: Duns stands for 'Data Universal Numbering System'. It is a nine-digit number issued by D&B (Dun & Bradstreet) and assigned to each business location in the D&B database having a unique, separate, and distinct operation to businesses for the purpose of identifying them.

    createdOn:
        type: string
    changedOn:
        type: string
    changedBy:
        type: string
    createdBy:
        type: string
example: !include ../examples/Supplier.json
