type: object
displayName: SupplierBankAccount
description: Object representing all bank accounts assigned to a given supplier.
properties:
    id:
        type: integer
    bankAccountId:
        type: string
    supplierId:
        type: string
    accountNumber:
        type: string
        description: The International Bank Account Number (IBAN).
    bankIdentificationCode:
        type: string
        description: Bank Identifier Code (BIC).
    swiftCode:
        type: string
        description: Society for Worldwide Interbank Financial Telecommunication (SWIFT) Code. Same as BIC
    bankCountryKey:
        type: string
        description: The bank's country as in ISO 3166-1 alpha2.
    extBankControlKey:
        type: string
    bankCode:
        type: string
        required: false
    bankName:
        type: string
    createdBy:
        type: string
    changedBy:
        type: string
    createdOn:
        type: string
    changedOn:
        type: string
example: !include ../examples/SupplierBankAccount.json
