displayName: Suppliers
description: Work with `Supplier` objects.
get:
    description: List of `Supplier` objects.
    responses:
        200:
            body:
                application/json:
                    type: SupplierArray
post:
    description: Adds a new supplier.
    body:
        application/json:
            type: Supplier
    responses:
        200:
            body:
                application/json:
                    type: Supplier
        409:
            description:
                A supplier with the same supplierId but different set of properties already exists.
/{supplierId}:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
    get:
        description: Single `Supplier` object.
        responses:
            200:
                body:
                    application/json:
                        type: Supplier
    put:
        description: Updates a supplier.
        body:
            application/json:
                type: Supplier
        responses:
            200:
                body:
                    application/json:
                        type: Supplier
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data
/{supplierId}/addresses:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
    get:
        description: Get all addresses assigned to the Supplier
        responses:
            200:
                body:
                    application/json:
                        type: SupplierAddressArray
    post:
        description: Insert Supplier to Address association
        body:
            application/json:
                type: SupplierAddress
        responses:
            200:
                body:
                    application/json:
                        type: SupplierAddress
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data
/{supplierId}/addresses/{addressId}:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
        addressId:
            type: number
            description: Identifeir of supplier address
    get:
        description: Get single `SupplierAddress` object assigned to the Supplier
        responses:
            200:
                body:
                    application/json:
                        type: SupplierAddress
    put:
        description: Update Supplier to Address association
        body:
            application/json:
                type: SupplierAddress
        responses:
            200:
                body:
                    application/json:
                        type: SupplierAddress
            409:
                description:
                    A supplier with the same supplierId but different set of properties already exists.
    delete:
        description: Delete SupplierAddress association
        responses:
            200:
                body:
                    application/json:
                        type: {}
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data

/{supplierId}/contacts:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
    get:
        description: Get all contacts assigned to the Supplier
        responses:
            200:
                body:
                    application/json:
                        type: SupplierContactsArray
    post:
        description: Insert new Contact association fro Supplier
        body:
            application/json:
                type: SupplierContact
        responses:
            200:
                body:
                    application/json:
                        type: SupplierContact
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data
/{supplierId}/contacts/{contactId}:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
        contactId:
            type: string
            description: Identifier of Supplier to Contact association
    get:
        description: Get single `SupplierContact` object assigned to the Supplier
        responses:
            200:
                body:
                    application/json:
                        type: SupplierContact
    put:
        description: Update SupplierContact association
            body:
                application/json:
                    type: SupplierContact
        responses:
            200:
                body:
                    application/json:
                        type: SupplierContact
            409:
                description:
                    A supplier with the same supplierId but different set of properties already exists.
    delete:
        description: Delete SupplierContact association
        responses:
            200:
                body:
                    application/json:
                        type: {}
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data

/{supplierId}/bank_accounts:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
    get:
        description: Get all bank accounts assigned to the Supplier
        responses:
            200:
                body:
                    application/json:
                        type: SupplierBankAccountArray
    post:
        description: Insert Bank Account to Supplier
        body:
            application/json:
                type: SupplierBankAccount
        responses:
            200:
                body:
                    application/json:
                        type: SupplierBankAccount
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data
/{supplierId}/bank_accounts/{bankAccountId}:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
        bankAccountId:
            type: string
            description: Identifier of supplier bank account
    get:
        description: Get single `SupplierBankAccount` object assigned to the Supplier
        responses:
            200:
                body:
                    application/json:
                        type: SupplierBankAccount
    put:
        description: Update Supplier to Address association
        body:
            application/json:
                type: SupplierBankAccount
        responses:
            200:
                body:
                    application/json:
                        type: SupplierBankAccount
            409:
                description:
                    A supplier with the same supplierId but different set of properties already exists.
    delete:
        description: Delete SupplierBankAccount association
        responses:
            200:
                body:
                    application/json:
                        type: {}
            403:
                description: Operation is not authorized
            422:
                description: Inconsistent data

/{supplierId}/profile_strength:
    uriParameters:
        supplierId:
            type: string
            description: Identifier of a supplier.
    get:
        description: Get supplier profile strength. It's a percentage value - integer between 0 and 100.
        responses:
            200:
                body:
                    application/json:
                        type: 42
